### PR TITLE
Issue 121: Proved that nat_decimal_string, nat_binary_string, and nat_hex_string are injective. Rewrote the nat to string conversion functions.

### PR DESCRIPTION
**Pull request by llee454**

### CODE REVIEW

**Comment by vmurali** [comment]
Shouldn't we merge natToHexStr and nat_hex_string - they are literally the same functions.

**Comment by llee454** [comment]
- [ ] update the pmp register names so that they use natToHexStr
- [ ] test the natToHexStr function on a large nat and compare execution time against original function
- [ ] move natToHexStr to a new file in Kami/Lib.

**Comment by llee454** [comment]
There was no observable slowdown when converting large nats to strings using the new natToHexStr function. The following is an example time result:

**Comment by llee454** [comment]
- [ ] remove commented code.

**Pull request merged**
