### PR TITLE
Add preliminary nomatch directives for simpl and Kami unfold database

### PR DESCRIPTION
**Pull request by jaykru**
This PR works towards addressing #31. 

I have added `simpl nomatch` directives to definitions and fixpoints obviously containing a match, but it may be necessary to make another pass through and add `simpl nomatch` directives for any definitions referring to an identifier with a match inside it.

### CODE REVIEW

**Comment by jaykru** [comment]
All the necessary `simpl nomatch` directives have been added. I am a bit unsure about the autounfold db I've made though, if only because the order in which we unfold particular identifiers (e.g. List.length before List.seq) has had a big effect on runtime and memory consumption subsequent reduction steps, and I see no easy way to control that in this scheme.

**Comment by vmurali** [comment]
Why does github show the entire file to be changed ?

**Comment by jaykru** [comment]
I think it's a newline format thing. Hiding whitespace changes on Github shows the right diff. Not sure why it changed...

**Comment by jaykru** [comment]
OK, newline format issue should be fixed.

**Comment by jaykru** [comment]
I've found at least two cases in Kami where having added `simpl nomatch` to a definition breaks proofs that rely on simpl unfolding that definition down to a match. I am guessing dependency on this behavior is pervasive and appears throughout Kami's dependencies. Should I fix all of those proofs with manual unfolding or just remove the offending `simpl nomatch` directive?

**Pull request merged**
